### ISSUE TITLE
cannot import 'model_urls'

### ISSUE THREAD

**Issue by vsatyamesc** [yunwoong7/korean_ocr_using_pororo#2]
ImportError: cannot import name 'model_urls' from 'torchvision.models.vgg' (C:\Users\XYZ\AppData\Local\Programs\Python\Python310\lib\site-packages\torchvision\models\vgg.py)

**Comment by vsatyamesc** [comment]
Also it depends on Torch 1.6.0 and torchvision 0.7.0 and these aren't available anymore

**Comment by yangjun-ux** [comment]
@SatyamSSJ10 
Install torchvision === 0.13
