### ISSUE TITLE
pip error: torch, torchvision incompatible

### ISSUE THREAD

**Issue by lukebayesian** [yunwoong7/korean_ocr_using_pororo#3]
Hello.

Raise issue because, I was attempt to try to use "pororo" but got error like below

pororo 0.4.2 requires torch==1.6.0, but you have torch 2.0.1 which is incompatible.
pororo 0.4.2 requires torchvision==0.7.0, but you have torchvision 0.15.2 which is incompatible.

To solve these, I did pip install torch==1.6.0 but got below error.

ERROR: Could not find a version that satisfies the requirement torch==1.6.0 (from versions: 1.7.1, 1.7.1+cpu, 1.7.1+cu101, 1.7.1+cu110, 1.8.0, 1.8.0+cpu, 1.8.0+cu101, 1.8.0+cu111, 1.8.1, 1.8.1+cpu, 1.8.1+cu101, 1.8.1+cu102, 1.8.1+cu111, 1.9.0, 1.9.0+cpu, 1.9.0+cu102, 1.9.0+cu111, 1.9.1, 1.9.1+cpu, 1.9.1+cu1
02, 1.9.1+cu111, 1.10.0, 1.10.0+cpu, 1.10.0+cu102, 1.10.0+cu111, 1.10.0+cu113, 1.10.1, 1.10.1+cpu, 1.10.1+cu102, 1.10.1+cu111, 1.10.1+cu113, 1.10.2, 1.10.2+cpu, 1.10.2+cu102, 1.10.2+cu111, 1.10.2+cu113, 1.11.0, 1.11.0+cpu, 1.11.0+cu113, 1.11.0+cu115, 1.12.0, 1.12.0+cpu, 1.12.0+cu113, 1.12.0+cu116, 1.12.1, 1.12.
1+cpu, 1.12.1+cu113, 1.12.1+cu116, 1.13.0, 1.13.0+cpu, 1.13.0+cu116, 1.13.0+cu117, 1.13.1, 1.13.1+cpu, 1.13.1+cu116, 1.13.1+cu117, 2.0.0, 2.0.0+cpu, 2.0.0+cu117, 2.0.0+cu118, 2.0.1, 2.0.1+cpu, 2.0.1+cu117, 2.0.1+cu118)
ERROR: No matching distribution found for torch==1.6.0

How am i supposed to solve it?

**Comment by yunwoong7** [comment]
The error message "Could not find a version that satisfies the requirement torch==1.6.0" generally occurs when you're trying to install a specific version of PyTorch that isn't available or compatible with your current environment.

For torch 1.6.0, it only supports Python versions up to 3.8. If you're using a different Python version, you might need to switch to a compatible version.

For the Pororo library, I used Python version 3.7.13 with torch version 1.13.1, and it worked without any problems.

**Comment by lukebayesian** [comment]
Thanks for your reply.

I'm using 3.9 series of python version and what I've understood is,
the "Pororo" only runs with 3.8 python version which it means that i have to use 3.8 python version.

Am i getting right?

**Comment by yunwoong7** [comment]
To be more precise, the version of torch you're trying to install is not supported on your current Python version. You can either downgrade your Python version to install torch, or upgrade the version of torch. However, after installation, there could be more considerations depending on your environment, so I recommend downgrading your Python version and proceeding.

**Comment by lukebayesian** [comment]
Okay.
Downgrade to 3.8 and install torch==1.6.0. Got it.
Thank you for your concern. :)

**Comment by abhyArgosdyne** [comment]
> The error message "Could not find a version that satisfies the requirement torch==1.6.0" generally occurs when you're trying to install a specific version of PyTorch that isn't available or compatible with your current environment.
> 
> For torch 1.6.0, it only supports Python versions up to 3.8. If you're using a different Python version, you might need to switch to a compatible version.
> 
> For the Pororo library, I used Python version 3.7.13 with torch version 1.13.1, and it worked without any problems.

Hello, how did you use torch version 1.13.1 when the requirement is strict for 1.6.0 by pororo pip installation? 
Also, I tried python 3.6.9 and 3.8 but torch 1.6.0 are not available. So, what do you suggest I should do now?
