### ISSUE TITLE
Can you please test this repo  on the following Image

### ISSUE THREAD

**Issue by yhammadmufin** [yunwoong7/korean_ocr_using_pororo#4]
Can you please test this repo on the following Image?
![image (2)](https://github.com/yunwoong7/korean_ocr_using_pororo/assets/129506205/9294e2c5-3657-4ac1-8116-f9ce8faa39c7)

**Comment by shreyanshu09** [comment]
This is the result from this repo.

![4](https://github.com/yunwoong7/korean_ocr_using_pororo/assets/33536680/bfdb74e4-dab9-48b5-8535-48d9e9b3c68c)
